[package]
name = "liblinear"
version = "0.1.0"
authors = ["Madeesh Kannan", "Peter Schoener"]

build = "build.rs"
links = "liblinear.a"

description = "Rust bindings for the liblinear C library"
repository = "https://github.com/shadeMe/liblinear-rs"
keywords = ["machine learning", "statistics", "svm", "support vector machines"]
license = "MIT"

[dependencies]
failure = "0.1.2"
num = "0.2.0"
num-derive = "0.2.2"
num-traits = "0.2.6"
parsnip = "0.3.0"
approx = "0.3.0"

[build-dependencies]
cc = "1.0"